### ISSUE TITLE
GhostInstall doesn't work Had to use `pip3` on arch linux

### ISSUE THREAD

**Issue by charlespwd** [raghur/vim-ghost#24]
First, this is pretty cool. I was able to write this PR message inside
of nvim. Nice.

I had issues with `GhostInstall`. Somehow I think the dependencies
were installed with `pip` which is aliased to `pip2` on my system.
Might be a better idea to use `pip3`.

Once I installed both python-slugify and the other dep manually with
`pip3 install --user`, everything worked flawlessly.

This is trully awesome and remarkable. Great work!

**Comment by raghur** [comment]
hmm - I recently rewrote the installer script in python - also pip isn't invoked directly - instead it's invoked as `python -m pip` so that py2 version isn't invoked accidentally.

If you don't mind, can you remove the deps and install from master again?

**Comment by klmr** [comment]
FYI, I’m having the same issue (and there seem to be more people) on macOS:
`GhostInstall` fails due to missing `SimpleWebSocketServer` and `slugify`. After
installing them manually, it works (I’m writing this from Vim).

Probably related to #8.

**Comment by gibfahn** [comment]
FWIW works for me with homebrew python2 and python3 installed, I had to update due to https://github.com/raghur/vim-ghost/pull/27, but otherwise seems to work as expected.

**Comment by raghur** [comment]
Closing due to inactivity. Please feel free to reopen if you still see this.

**Comment by azenan** [comment]
Also had this issue on Arch.

```
➜ nvim --version
NVIM v0.3.1
```
Installing the requirements manually worked fine as others have said.

Output from the `:GhostInstall` command:

```
:GhostInstall
ghost: installing dependencies from /home/mthomas/.vim/plugged/vim-ghost/requirements_posix.txt
ghost:
ghost: dependencies installed successfully
Encountered ModuleNotFoundError loading plugin at /home/mthomas/.dotfiles/vim/plugged/vim-ghost/rplugin/python3/ghost.py: No module na
med 'slugify'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pynvim/plugin/host.py", line 135, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
ModuleNotFoundError: No module named 'slugify'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/mthomas/.local/share/nvim/rplugin.vim
:UpdateRemotePlugins executed. Please restart nvim
Press ENTER or type command to continue
```

**Comment by raghur** [comment]
I just pushed another fix for the installer. Can you test? you'll need to `pip uninstall simplewebsocketserver python-slugify` first to make sure you have a blank env. Then run `:GhostInstall` from vim/nvim

**Comment by azenan** [comment]
That seems to have done the trick. Thanks!

```
ghost: installing dependencies from /home/mthomas/.vim/plugged/vim-ghost/requirements_posix.txt                                                                                                                                                                     
ghost: Collecting git+https://github.com/dpallot/simple-websocket-server.git (from -r /home/mthomas/.vim/plugged/vim-ghost/requirements_posix.txt (line 1))
ghost:   Cloning https://github.com/dpallot/simple-websocket-server.git to /tmp/pip-req-build-mx79ov58
ghost: Collecting python-slugify (from -r /home/mthomas/.vim/plugged/vim-ghost/requirements_posix.txt (line 2))
ghost:   Using cached https://files.pythonhosted.org/packages/1f/9c/8b07d625e9c9df567986d887f0375075abb1923e49d074a7803cd1527dae/python-slugify-2.0.1.tar.gz
ghost: Requirement already satisfied: Unidecode>=0.04.16 in /home/mthomas/.local/lib/python3.7/site-packages (from python-slugify->-r /home/mthomas/.vim/plugged/vim-ghost/requirements_posix.txt (line 2)) (1.0.23)
ghost: Installing collected packages: python-slugify, SimpleWebSocketServer
ghost:   Running setup.py install for python-slugify: started
ghost:     Running setup.py install for python-slugify: finished with status 'done'
ghost:   Running setup.py install for SimpleWebSocketServer: started
ghost:     Running setup.py install for SimpleWebSocketServer: finished with status 'done'
ghost: Successfully installed SimpleWebSocketServer-0.1.0 python-slugify-2.0.1
ghost:
ghost: dependencies installed successfully
remote/host: python3 host registered plugins ['ghost.py']
remote/host: generated rplugin manifest: /home/mthomas/.local/share/nvim/rplugin.vim
:UpdateRemotePlugins executed. Please restart nvim
Press ENTER or type command to continue
```
