### ISSUE TITLE
GhostInstall issue with default setup

### ISSUE THREAD

**Issue by toastal** [raghur/vim-ghost#40]
The last few days I've had issues with this plugin and `GhostInstall` after an update. I tried a fresh install. The Neovim windows says this.
```
ghost: installing dependencies from $HOME/.config/nvim/plugged/vim-ghost/requirements_posix.txt
ghost: error installing dependencies: Command '['/sbin/python3', '-m', 'pip', 'install', '--user', '-r', '$HOME/.config/nvim/plugged/vim-ghost/requirements_posix.txt'
]' returned non-zero exit status 1.
Encountered ModuleNotFoundError loading plugin at $HOME/config/nvim/plugged/vim-ghost/rplugin/python3/ghost.py: No module named 'SimpleWebSocketServer'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ModuleNotFoundError: No module named 'SimpleWebSocketServer'
remote/host: python3 host registered plugins ['LanguageClient', 'denite']
remote/host: generated rplugin manifest: $HOME/.local/share/nvim/rplugin.vim
:UpdateRemotePlugins executed. Please restart nvim
```

When I tried to run the command it seems the script is trying to run `python3 -m pip install --user -r requirements_posix.txt` from the `$HOME/.config/neovim/plugged/vim-ghost` folder I got:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 16, in <module>
    from pip._internal.distributions import (
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/__init__.py", line 2, in <module>
    from pip._internal.distributions.wheel import WheelDistribution
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/wheel.py", line 5, in <module>
    from pip._internal.utils.wheel import pkg_resources_distribution_for_wheel
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/wheel.py", line 12, in <module>
    from pip._vendor.six import PY2, ensure_str
ImportError: cannot import name 'ensure_str' from 'six' ($HOME/.local/lib/python3.8/site-packages/six.py)
```

Somewhere I package isn't getting installed and there's some issue with an import somewhere too. I've not used Python in _years_ though so I don't know much about what this error output means.

For context:
Operating System: Arch Linux
Kernel: Linux 5.7.2-zen1-1-zen
Architecture: x86-64
Python 3.8.3
pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)

**Comment by raghur** [comment]
See if this helps you - https://stackoverflow.com/questions/61727705/pyhton-pip-importerror-cannot-import-name-ensure-str-from-six-on-multiple

**Comment by toastal** [comment]
Ah, this does seem to be an issue with my OS specifically. I don't really mess with Python so I'm curious how my system got corrupted. Either way, it doesn't seem relevant to this.
