### ISSUE TITLE
slugify not in requires

### ISSUE THREAD

**Issue by SkyLeach** [raghur/vim-ghost#8]
If you attempt to use `:GhostInstall` without already having used `pip install python-slugify` it will not work.

Also, if you try `pip install slugify` you'll get an exception.  It claims to be python3 compliant, but it isn't because it still attempts to use `unicode()` which isn't a function in python3.

**Comment by raghur** [comment]
Note - the module is `python-slugify` - not `slugify`. It's present in requirements_posix and requirements_win

see 
https://github.com/raghur/vim-ghost/blob/125d1299a0b7d354acaeadee84a0503050c850e0/requirements_posix.txt#L2

**Comment by SkyLeach** [comment]
I'm on darwin (mac) so that's why then.

**Comment by raghur** [comment]
Are you saying that the install script (./install) isn't run on a mac? I don't have a mac to test but the code in `:GhostInstall` basically forms the path to `./install` and executes it. So only on windows, it will install the install.cmd and everywhere else it should run the ./install script.

**Comment by SkyLeach** [comment]
I'm saying that on darwin (mac) the slugify requirement isn't being pulled in.

here, I'll uninstall slugify and paste the traceback from `:GhostInstall`:
```
GhostInstall  GhostStart  GhostStop
Encountered ModuleNotFoundError loading plugin at /Users/magregor/.config/nvim/bundle/vim-ghost/rplugin/python3/ghost.py: No module named 'slugify'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/neovim/plugin/host.py", line 130, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ModuleNotFoundError: No module named 'slugify'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/magregor/.local/share/nvim/rplugin.vim
:UpdateRemotePlugins executed. Please restart nvim
Press ENTER or type command to continue
```

**Comment by raghur** [comment]
Thank you. What happens if you run the ./install from a shell?

**Comment by SkyLeach** [comment]
It's slightly modified due to issue #9 

```
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ MACHINE (user)
| => cat install
#!/usr/bin/env bash
which python3
python3 -mpip install --user -r requirements_posix.txt
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ MACHINE (user)
| => ./install
/usr/local/bin/python3
Collecting git+https://github.com/dpallot/simple-websocket-server.git (from -r requirements_posix.txt (line 1))
  Cloning https://github.com/dpallot/simple-websocket-server.git to /private/var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-vch8k674-build
  Requirement already satisfied (use --upgrade to upgrade): SimpleWebSocketServer==0.1.0 from git+https://github.com/dpallot/simple-websocket-server.git in /usr/local/lib/python3.6/site-packages (from -r requirements_posix.txt (line 1))
Requirement already satisfied: python-slugify in /Users/user/Library/Python/3.6/lib/python/site-packages (from -r requirements_posix.txt (line 2))
Requirement already satisfied: Unidecode>=0.04.16 in /usr/local/lib/python3.6/site-packages (from python-slugify->-r requirements_posix.txt (line 2))
```

After restarting vimr (or nvim from the shell):

```
remote/host: python3 host registered plugins ['ghost.py']
remote/host: generated rplugin manifest: /Users/magregor/.local/share/nvim/rplugin.vim
:UpdateRemotePlugins executed. Please restart nvim
Press ENTER or type command to continue
```

So it does look like manually running it will fix the install issue.  I did, however, modify the install script a bit for more information and to run the correct version of bash.  Let me go now and undo those changes and see what happens....

```
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => pip uninstall python-slugify
Uninstalling python-slugify-1.2.4:
  /Users/user/Library/Python/3.6/bin/slugify
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/DESCRIPTION.rst
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/INSTALLER
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/METADATA
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/RECORD
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/WHEEL
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/entry_points.txt
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/metadata.json
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/top_level.txt
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/__init__.py
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/__pycache__/__init__.cpython-36.pyc
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/__pycache__/slugify.cpython-36.pyc
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/slugify.py
Proceed (y/n)? y
  Successfully uninstalled python-slugify-1.2.4
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => nvim install
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => ./install
/usr/local/bin/python3
Collecting git+https://github.com/dpallot/simple-websocket-server.git (from -r requirements_posix.txt (line 1))
  Cloning https://github.com/dpallot/simple-websocket-server.git to /private/var/folders/kt/yxsj572j6z18h6gq073_zvdr0000gn/T/pip-aezr4pac-build
  Requirement already satisfied (use --upgrade to upgrade): SimpleWebSocketServer==0.1.0 from git+https://github.com/dpallot/simple-websocket-server.git in /usr/local/lib/python3.6/site-packages (from -r requirements_posix.txt (line 1))
Collecting python-slugify (from -r requirements_posix.txt (line 2))
  Using cached python_slugify-1.2.4-py2.py3-none-any.whl
Requirement already satisfied: Unidecode>=0.04.16 in /usr/local/lib/python3.6/site-packages (from python-slugify->-r requirements_posix.txt (line 2))
Installing collected packages: python-slugify
Successfully installed python-slugify-1.2.4
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => nvim
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => vim ~/.local/share/nvim/rplugin.vim
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => rm -fv ~/.local/share/nvim/rplugin.vim
/Users/user/.local/share/nvim/rplugin.vim
```

So yeah, running from my bash shell works, but it doesn't appear that running through vimr does.  I just double-checked by running `pip uninstall` and re-trying `:GhostInstall` in both console nvim and rvim.  Console worked, vimr did not.  Gotta be environment.

![screen shot 2018-03-23 at 11 39 26 am](https://user-images.githubusercontent.com/940228/37838651-e21070f0-2e8e-11e8-8140-e7a0b6f409fe.png)

**Comment by SkyLeach** [comment]
```
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => git checkout master
M       install
M       rplugin/python3/ghost.py
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   install
        modified:   rplugin/python3/ghost.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        doc/tags

no changes added to commit (use "git add" and/or "git commit -a")
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => git log -n1
commit 125d1299a0b7d354acaeadee84a0503050c850e0 (HEAD -> master, origin/master, origin/HEAD, localhost_bind)
Author: Raghu Rajagopalan <raghu.rajagopalan@gmail.com>
Date:   Wed Mar 7 12:57:21 2018 +0530

    install: use python -mpip to handle cases where multiple python3 versions may be installed
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => pip uninstall python-slugify
Uninstalling python-slugify-1.2.4:
  /Users/user/Library/Python/3.6/bin/slugify
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/DESCRIPTION.rst
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/INSTALLER
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/METADATA
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/RECORD
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/WHEEL
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/entry_points.txt
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/metadata.json
  /Users/user/Library/Python/3.6/lib/python/site-packages/python_slugify-1.2.4.dist-info/top_level.txt
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/__init__.py
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/__pycache__/__init__.cpython-36.pyc
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/__pycache__/slugify.cpython-36.pyc
  /Users/user/Library/Python/3.6/lib/python/site-packages/slugify/slugify.py
Proceed (y/n)? y
  Successfully uninstalled python-slugify-1.2.4
________________________________________________________________________________
| ~/.config/nvim/bundle/vim-ghost @ HOST (user)
| => rm -fv ~/.local/share/nvim/rplugin.vim
/Users/user/.local/share/nvim/rplugin.vim
```

still works, so I guess it's just rvim.
